version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database   
      POSTGRES_USER: admin      
      POSTGRES_PASSWORD: admin   
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
