# myapp/models.py
from django.db import models

class Dados(models.Model):
    PRINCIPIO_ATIVO = models.CharField(max_length=100)
    CNPJ = models.CharField(max_length=100)
    LABORATORIO = models.CharField(max_length=100)
    CODIGO_GGREM = models.CharField(max_length=100)
    REGISTRO = models.CharField(max_length=100)
    EAN1 = models.CharField(max_length=100)
    EAN2 = models.CharField(max_length=100)
    EAN3 = models.CharField(max_length=100)
    PRODUTO = models.CharField(max_length=100)
    APRESENTACAO = models.CharField(max_length=100)
    CLASSE_TERAPEUTICA = models.CharField(max_length=100)
    TIPO_PRODUTO = models.CharField(max_length=100)
    REGIME_PRECO = models.CharField(max_length=100)
    PF_SEM_IMPOSTOS = models.CharField(max_length=100)
    PF_0 = models.CharField(max_length=100)
    PF_12 = models.CharField(max_length=100)
    PF_17 = models.CharField(max_length=100)
    PF_17_ALC = models.CharField(max_length=100)
    PF_17_5 = models.CharField(max_length=100)
    PF_17_5_ALC = models.CharField(max_length=100)
    PF_18 = models.CharField(max_length=100)
    PF_18_ALC = models.CharField(max_length=100)
    PF_19 = models.CharField(max_length=100)
    PF_20 = models.CharField(max_length=100)
    PF_21 = models.CharField(max_length=100)
    PF_22 = models.CharField(max_length=100)
    PMVG_SEM_IMPOSTOS = models.CharField(max_length=100)
    PMVG_0 = models.CharField(max_length=100)
    PMVG_12 = models.CharField(max_length=100)
    PMVG_17 = models.CharField(max_length=100)
    PMVG_17_ALC = models.CharField(max_length=100)
    PMVG_17_5 = models.CharField(max_length=100)
    PMVG_17_5_ALC = models.CharField(max_length=100)
    PMVG_18 = models.CharField(max_length=100)
    PMVG_18_ALC = models.CharField(max_length=100)
    PMVG_19 = models.CharField(max_length=100)
    PMVG_20 = models.CharField(max_length=100)
    PMVG_21 = models.CharField(max_length=100)
    PMVG_22 = models.CharField(max_length=100)
    RESTRICAO_HOSPITALAR = models.CharField(max_length=100)
    CAP = models.CharField(max_length=100)
    CONFAZ_87 = models.CharField(max_length=100)
    ICMS_0 = models.CharField(max_length=100)
    ANALISE_RECURSAL = models.CharField(max_length=100)
    LISTA_CONCESSAO_CREDITO = models.CharField(max_length=100)
    COMERCIALIZACAO_2022 = models.CharField(max_length=100)
    TARJA = models.CharField(max_length=100)


    def _str_(self):
        return self.campo1