# Generated by Django 4.2.3 on 2023-07-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRINCIPIO_ATIVO', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=100)),
                ('LABORATORIO', models.CharField(max_length=100)),
                ('CODIGO_GGREM', models.CharField(max_length=100)),
                ('REGISTRO', models.CharField(max_length=100)),
                ('EAN1', models.CharField(max_length=100)),
                ('EAN2', models.CharField(max_length=100)),
                ('EAN3', models.CharField(max_length=100)),
                ('PRODUTO', models.CharField(max_length=100)),
                ('APRESENTACAO', models.CharField(max_length=100)),
                ('CLASSE_TERAPEUTICA', models.CharField(max_length=100)),
                ('TIPO_PRODUTO', models.CharField(max_length=100)),
                ('REGIME_PRECO', models.CharField(max_length=100)),
                ('PF_SEM_IMPOSTOS', models.CharField(max_length=100)),
                ('PF_0', models.IntegerField(max_length=100)),
                ('PF_12', models.IntegerField(max_length=100)),
                ('PF_17', models.IntegerField(max_length=100)),
                ('PF_17_ALC', models.IntegerField(max_length=100)),
                ('PF_17_5', models.IntegerField(max_length=100)),
                ('PF_17_5_ALC', models.IntegerField(max_length=100)),
                ('PF_18', models.IntegerField(max_length=100)),
                ('PF_18_ALC', models.IntegerField(max_length=100)),
                ('PF_19', models.IntegerField(max_length=100)),
                ('PF_20', models.IntegerField(max_length=100)),
                ('PF_21', models.IntegerField(max_length=100)),
                ('PF_22', models.IntegerField(max_length=100)),
                ('PMVG_SEM_IMPOSTOS', models.CharField(max_length=100)),
                ('PMVG_0', models.IntegerField(max_length=100)),
                ('PMVG_12', models.IntegerField(max_length=100)),
                ('PMVG_17', models.IntegerField(max_length=100)),
                ('PMVG_17_ALC', models.IntegerField(max_length=100)),
                ('PMVG_17_5', models.IntegerField(max_length=100)),
                ('PMVG_17_5_ALC', models.IntegerField(max_length=100)),
                ('PMVG_18', models.IntegerField(max_length=100)),
                ('PMVG_18_ALC', models.IntegerField(max_length=100)),
                ('PMVG_19', models.IntegerField(max_length=100)),
                ('PMVG_20', models.IntegerField(max_length=100)),
                ('PMVG_21', models.IntegerField(max_length=100)),
                ('PMVG_22', models.IntegerField(max_length=100)),
                ('RESTRICAO_HOSPITALAR', models.CharField(max_length=100)),
                ('CAP', models.CharField(max_length=100)),
                ('CONFAZ_87', models.IntegerField(max_length=100)),
                ('ICMS_0', models.IntegerField(max_length=100)),
                ('ANALISE_RECURSAL', models.CharField(max_length=100)),
                ('LISTA_CONCESSAO_CREDITO', models.CharField(max_length=100)),
                ('COMERCIALIZACAO_2022', models.CharField(max_length=100)),
                ('TARJA', models.CharField(max_length=100)),
            ],
        ),
    ]
